#!/usr/bin/env python

import sys

import core_runner
from core_runner import PY_BASE, JS_BASE, PY_FILES, JS_FILES

core_runner.CHECKS = [
        dict(
                output="Running the Django validation tool...",
                command='''$VIRTUAL_ENV/bin/python manage.py validate'''
            ),
        dict(
                label="print/pprint statements",
                command=PY_BASE + '''--ignore-dir=cli --ignore-dir=management --ignore-dir=commands --ignore-dir=migrations --ignore-dir=tests "(^\s+p?print\s?\(?)|\.pprint\(" {0} 1>&2''',
                filter=PY_FILES,
                expect=1
            ),
        dict(
                label="console.log()",
                command=JS_BASE + '''console\.log {0}''',
                filter=JS_FILES,
                expect=1
            )
    ] + core_runner.python_checks

sys.exit(core_runner.main())
