#!/usr/bin/env python

import sys

import core_runner
from core_runner import PY_BASE, PY_FILES

core_runner.CHECKS = [
        dict(
                label="pprint statements",
                command=PY_BASE + '''"(^\s+pprint\s?\(?)|\.pprint\(" {0} 1>&2''',
                filter=PY_FILES,
                expect=1
            )
    ] + core_runner.python_checks

sys.exit(core_runner.main())
